---
title: "Untitled"
author: "José Monzón Egana"
date: "11/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown - https://ga-dev-tools.web.app/dimensions-metrics-explorer/

```{r setup, include=FALSE}
library(tidyverse)
library(magrittr)
```

```{r}
devtools::install_github("Tatvic/RGoogleAnalytics")
```
```{r}
install.packages('googleAnalyticsR')
library(googleAnalyticsR)
```

```{r}
ga_auth()
```
```{r}
my_accounts <- ga_account_list()
```
```{r}
view(my_accounts)
```
```{r}
# dimension1 = No transactions
metric1 <- met_filter("transactions","LESS_THAN",1)
metric2 <- met_filter("users","GREATER_THAN",1)

```
```{r}
mfilters <- filter_clause_ga4(list(metric1,metric2),operator = "AND")

```

```{r}
ga_id <- 139359521
```

filtering for dates
```{r}
yesterday <- Sys.Date() - 1
threeDaysAgo <- Sys.Date() - 3
ThirtyDaysAgo <- Sys.Date() - 30
SixMonthsAgo <- Sys.Date()-183
OneYearAgo <- Sys.Date()-365
FiveYearsAgo <- Sys.Date()-1827
```
Sessions during the last calendar year
```{r}
galastyear <- google_analytics(ga_id, date_range = c(OneYearAgo , yesterday), metrics = c("sessions"), 
                                         dimensions = c("date"))
str(galastyear)
galastyear %>%
  ggplot(aes(x = date,y = sessions) ) + 
  geom_point() + 
  geom_line() +
  geom_smooth(method = "loess") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

Transactions during the last year, it correlates pretty much with the sessions graph from above
```{r}
galastyeartr <- google_analytics(ga_id, date_range = c(OneYearAgo , yesterday), metrics = c("transactions"), 
                                         dimensions = c("date"))
str(galastyeartr)
galastyeartr %>%
  ggplot(aes(x = date,y = transactions) ) + 
  geom_point() + 
  geom_line() +
  geom_smooth(method = "loess") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
sessions during the last 30 days
```{r}
galastthirtydays <- google_analytics(ga_id, date_range = c(ThirtyDaysAgo , yesterday), metrics = c("sessions"), 
                                         dimensions = c("date"))
str(galastthirtydays) 
galastthirtydays %>%
  ggplot(aes(x = date,y = sessions) ) + 
  geom_point() + 
  geom_line() +
  geom_smooth(method = "loess") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

Sessions during the days of the week
```{r}
gadow <- google_analytics(ga_id, 
                           date_range = c(OneYearAgo , yesterday), 
                           metrics = c("sessions"), 
                           dimensions = c("dayOfWeekName","date"))
gadow %>%  
  ggplot(aes(x = dayOfWeekName, y = sessions)) + 
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
gadow[gadow$sessions < 50,] %>%  
  ggplot(aes(x = dayOfWeekName, y = sessions)) + 
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
ga5years <- google_analytics(ga_id, 
                          date_range = c(FiveYearsAgo, yesterday),
                          metrics = c("sessions"),
                          dimensions = c("date"), 
                          
                          max=-1)
```

Sessions in framacph.com during the last 5 years
```{r}
ga5years$year<-format(ga5years$date,"%Y")
ggplot(ga5years, aes(x=date, y=sessions, color=year)) + 
  geom_line() 
```
Tipe of device
```{r}
gadevice <- google_analytics(ga_id, 
                           date_range = c(OneYearAgo , yesterday),
                           metrics = c("sessions"),
                           dimensions = c("date","continent", "deviceCategory"), 
                           anti_sample = TRUE,
                           max=5000)
ggplot(gadevice[gadevice$continent != "(not set)",], aes(x=continent)) + 
  geom_bar(aes(fill=deviceCategory), position="fill")
```

